fsprojects/IfSharp

build.fsx
build.sh

Hi 
I have Ubuntu installed and F# 4.0 running on Mono on it. I have managed to run build.sh sucessfully after fixing a series of paths typos - case sensitive sort - in build.sh and build.fsx. While on Windows these would not pose problems, I'm sure you know that Linux is not that flexible. 
Might be worth merging this pull request, it won't affect Windows builds but will help Linux ones.

Make build.sh run on Linux

---

build.fsx
src/IfSharpConsole/App.config

This makes the Fake script ignore the lack of tests and so it builds without errors, giving a better impression for anyone trying to build this branch.

Fix ancient build

---

src/IfSharp.Kernel/DirectivePreprocessor.fs
src/IfSharp.Kernel/Evaluation.fs
src/IfSharp.Kernel/IfSharp.Kernel.fsproj
src/IfSharp.Kernel/Kernel.fs
src/IfSharp.Kernel/NuGetManager.fs

I extended the nuget manager to allow additional directives. This is so that people can turn on showing FSI output particularly for types #63 #43  e.g.
```
In [1]:
#fsioutput "on"
​
let x = 2
x
Out[1]:
val x : int = 2
val it : int = 2
Out[1]:
2
```
I also added trapping of #help as the other directives can also be useful.
Does this seem natural? We're peeling back the abstraction and letting people interact directly with the F# Interactive instance. So if you turn fsioutput on in one cell that will affect other cells until you turn it off again.

Add a new notebook specific directive "fsioutput" to capture outputs

---

.gitignore
src/IfSharp.Kernel/helpers/FSCharting.Gtk.fsx
src/IfSharp.Kernel/helpers/FSCharting.fsx
src/IfSharp.Kernel/helpers/XPlot.Plotly.fsx

This change automatically initialises Display printers and uses
`[<AutoOpen>]` to expose the extension methods. As a result, the
notebook user only needs to #load the helper script, and doesn't
need to know a module name to open or an initialisation function
to run.
This change uses `addDisplayPrinter` to make XPlot charts display
in the same way as other elements. It also changes the way the
plot.ly JavaScript is loaded such that it is loaded in the notebook
browser when the script is loaded, without needing an initialisation
call.
Plotly has many lovely features, but large data sets rendered as
JavaScript can be difficult to deal with. This adds Chart.Image,
which renders a chart as a static PNG.

Auto-Initialise XPlotly.Plotly.fsx and FSCharting.fsx

---

src/IfSharp.Kernel/App.fs

Previously, ifsharp.exe would always try to run jupyter. This is not
the desired behaviour in some instances (for example, in a Docker
container, where jupyter must be started with specific command line
options).
This change adds a `--install` option that installs the IfSharp
kernel without trying to start jupyter.

Install option

---

src/IfSharp.Kernel/helpers/Paket.fsx

This script loads `Paket.Core.dll` and sets up a `paket` object that
is an instance of `Paket.Dependencies` that is initialised from
`bin/paket.dependencies`. This allows simple use of Paket from
jupyter, like this:
```fsharp
Paket.Package
[ "Some.Package"
"Another.Package"
]
```

Add a Paket.fsx script

---

paket.dependencies
paket.lock
src/IfSharp.Kernel/Evaluation.fs
src/IfSharp.Kernel/IfSharp.Kernel.fsproj
src/IfSharp.Kernel/Printers.fs

This makes it possible to use `fsi.AddHtmlPrinter` in IFSharp, in the same way in which it is used in the Atom Ionide plugin. The implementation follows the example of the one in [FsInteractiveService](http://ionide.io/FsInteractiveService/), which also has some [documentation for creating HTML printers](http://ionide.io/FsInteractiveService/htmlprinter.html) - all this will now work in IFSharp too, so you can write portable HTML formatters.
Here is an example of two things that work for free in FsLab :-)
As a bonus, you can actually scroll in the displayed Deedle frame to see more rows. If you're using [Big Deedle](https://github.com/BlueMountainCapital/Deedle.BigDemo), this will work without actually fetching all the data, so you can do this over Big Data (tm).

Add support for FsLab-compatible AddHtmlPrinter

---

ipython-profile/kernel.js
kernel-spec/kernel.json

This correctly respects the kernelspecs path set by Jupyter. It also places the F# logo only in the "normal" place, allowing the Jupyter logo to display in the upper left (as other kernels do). The display name is changed from IFSharp (the kernel name) to F# (the language name) to match other kernels.

Kernelspecs

---

src/IfSharp.Kernel/Kernel.fs
src/IfSharp.Kernel/NuGetManager.fs

#N for getting NuGets is currently non-functional, see #106 
Paket is a generally better way to get NuGets and users would generally be better off switching to Paket now. This change gives some assistance in switching off #N syntax.
We would be able to remove the very old \lib\NuGet.dll if we were to do this.
The main missing feature is that the #N syntax also automatically referenced the dlls for you, see: `frameworkAssemblyReferences`.
We could either do without that given that Paket acquires packages without version numbers in the directories or attempt to implement it again in a cross-framework way.

Give users assistance converting from #N

---

src/IfSharp.Kernel/helpers/Paket.Generated.Refs.fsx
src/IfSharp.Kernel/helpers/Paket.fsx

This allows the start of the notebook to be like this:
```fsharp
#load "Paket.fsx"
Paket.Package
[ "MathNet.Numerics"
"MathNet.Numerics.FSharp"
]
#load "Paket.Generated.Refs.fsx"
```
I used Paket.Generated.Refs.fsx avoiding overlap with https://github.com/fsprojects/Paket/issues/1943 alternatively all-references.fsx could also work etc.
It's less noisy and there's less magic going on but still less explicit than getting users to reference their own dlls. Thoughts? Rather than extend the Package and Version functions, we could have a separate ReferencePackages() function.
it's encapsulated a lot of the other concerns compared to the full syntax in #106 
```fsharp
#load "Paket.fsx"
Paket.Dependencies.Install """
frameworks: net451
source https://nuget.org/api/v2
nuget MathNet.Numerics
nuget …
```

Generate the referencing scripts

---

paket.lock

When using Mono 4.8 and IfSharp the `generateScripts()` call in Paket.fsx was failing in paths with capitalised directory names. Paket 3.33.3 does not have this problem.

update paket version

---

src/IfSharp.Kernel/App.fs
src/IfSharp.Kernel/Evaluation.fs
src/IfSharp.Kernel/Kernel.fs

Attach a string builder as System.Console.Out and send its contents
to the notebook on Display and when execution completes.
Do not send a "pyout" message when the result of a cell is of type
unit, in order to avoid printing "<null>".

Display Standard Out

---

paket.lock
src/IfSharp.Kernel/App.fs
src/IfSharp.Kernel/Evaluation.fs
src/IfSharp.Kernel/IfSharp.Kernel.fsproj
src/IfSharp.Kernel/Kernel.fs
src/IfSharp.Kernel/Printers.fs
src/IfSharpConsole/IfSharpConsole.csproj
tests/IfSharp.Kernel.Tests/IfSharp.Kernel.Tests.fsproj

Change the default printer to respect all fsi print options,
including FloatingPointFormat, PrintLength, etc.
As part of this, switch to ParseAndCheckFileInProject for
IntelliSense and update dependencies to pick up FSharp.Compiler.Service
9.0.1.

Respect fsi print options

---

src/IfSharp.Kernel/Printers.fs

We print the last expression of a cell, which for some types like FSharpFunc leads to less information than on FSI:
```
In[1]: let addTwo = (+) 2
addTwo
Out[1]: <fun:addTwo@1-10>
```
As reported on #125. There are various workarounds e.g. .GetType().BaseType or as I suggest on the issue turning on fsioutput. That's nice to have as an option but for _functions_ we can have a better default:
```fsharp
let addTwo = (+) 2
addTwo
```
now produces:
```
<fun:addTwo@1-1> : (Int32 -> Int32)
```
It uses reflection rather than the F# which means everything is in CLR types so there are differences to FSI e.g.
```fsharp
let addHigher f g = ((f 2) 3) + (g 2 3) + 5
addHigher
```
in the notebook:
```
<fun:it@2> : ((Int32 -> (Int32 -> Int32)) -> ((Int32 -> (Int32 -> Int32)) -> Int32))
```
while fsi:
``` …
```

Provide function signature by default

---

README.md

There's a tiny typo in the URL for the linux manual installation section - it's currently a broken link

fix up the Download URL for the Manual Installation (Linux) section

---

Dockerfile

Use mono-image to get around certificate issues with Paket when using ubuntu:16.04
Add USER-statements to run as ifsharp-user (not use root)

Use mono:5.4.0.201 as base image and add USER

---

src/IfSharpConsole/IfSharpConsole.csproj

I get the following warnings when building in VS2017 (and the files should be included in the *.fsx include a couple of lines down)

Remove build warnings of files added twice

---

src/IfSharp.Kernel/Evaluation.fs

Thanks for the info from @dsyme , constraining the print length is a workaround to prevent StackOverflow exceptions during printing of nested sequences on Mono.
closes #143 closes #174 closes #169 here, keeping active issue mono/mono#8975 for the initial cause of the problem

Fixing #143 by constraining interactive printing length

---

ipython-profile/kernel.js
ipython-profile/static/custom/fsharp.css

A user has an ability to apply themes using projects like jupyter-themes (sets custom.css).
For an F# code in notebook VisualStudio-like colouring is applied.
Added white background for "dark" themes
Dark theme example:

Jupyter themes and VisualStudio theme for f#

---

src/IfSharp.Kernel/Kernel.fs
src/IfSharp.Kernel/ShellMessages.fs

This added the support for [comms](https://jupyter-client.readthedocs.io/en/stable/messaging.html#custom-messages). This can be considered as a part of #126 and #137 as Jupyter widgets are based on comms.
The comm identified by `target_name` now can be registered through specifying a set of callbacks.
E.g. in App.fs we can do the following
```F#
Kernel.Value.RegisterComm("echo-comm",
(fun send data -> ()), // comm onOpen callback
(fun send message -> // comm onMessage callback
send message.data), // here it sends received data back to the Frontend
(fun data -> ())) // comm onClose callback
```
The code in PR creates and destroys comm instances according to the Jupyter client protocol.
Maintains the opened comms, processes the comm messages through the callback which is specified during …

COMM messages support

---

src/IfSharp.Kernel/Evaluation.fs

It is reasonable for load scripts to configure themselves based on host.   We already have HAS_FSI_ADDHTMLPRINTER, and it is better to use host capabilities like this, but also having a host define is sensible.

Add IFSHARP define

---

src/IfSharp.Kernel/Util.fs

It makes #192 much cleaner, and abstracts away the hiding of RequireJS

Allow loading JavaScript scripts

---

Dockerfile

Received 2 separate errors during build
1. Build could not find 4.7.2 libraries.  This was fixed by upgrading mono version to 5.18 (latest).
2. Build could not run the pip3 command.  Fixed using advice from https://github.com/pypa/pip/issues/5221#issuecomment-382069604

Fix Docker compilation / build errors

---

Dockerfile

Adds Jupyter extension to Docker image for #199

Jupyter extensions in Docker image

---

src/IfSharp.Kernel/Evaluation.fs
src/IfSharp.Kernel/Kernel.fs

This is a fix for issue #201.
I have also cleaned up the whitespace in `src/IfSharp.Kernel/Evaluation.fs`.

Fix .Net core Intellisense issue

---

src/IfSharp/AssemblyInfo.fs
src/IfSharp/IfSharp.fsproj

There are quite a few assembly references which have incorrectly reference `IFSharp` rather than `IfSharp`. This PR just aims to make it more uniform.

Fixed incorrect assembly name references

---

RELEASE_NOTES.md
build.fsx

Uses RELEASE_NOTES.md 
Bumps version to 3.0.2

generate release notes and bump to 3.0.2

---

src/IfSharp.Kernel/Kernel.fs

Jupyter Labs is sending extra information in meta e.g. "deletedCells". We don't currently use this so avoid deserializing as there's a problem with that!
Note there are outstanding issues in Jupyter Labs:
- Code highlighting not enabled (using default)
- Code completion not enabled
- Plotting results not shown
They'll all need someone to follow up later but at least this loads and runs for me:

Workaround for Jupyter Labs 

---

src/IfSharp.Kernel/Evaluation.fs
src/IfSharp.Kernel/Kernel.fs

If expression can't be evaluated e.g. it's unconstrained then just give string

---

FSharp_Jupyter_Notebooks.ipynb
src/IfSharp.Kernel/Util.fs

Use the order of the propertyNames (when given) for the order of the columns in the table.
Updated example in `FSharp_Jupyter_Notebooks.ipynb`

Utils.Table propertyName order
